name: Codespace Auto-Run

on:
  workflow_dispatch:
    inputs:
      part:
        description: 'Part number (01, 02, etc.)'
        required: false
        default: '01'
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Display Start Time
        run: |
          echo "=== GitHub Codespace Auto-Run Script ==="
          echo "Start time: $(date)"

      - name: Install Required Packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y stress curl git jq

      - name: Install GitHub CLI
        run: |
          if ! command -v gh &> /dev/null; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update -y
            sudo apt install gh -y
          fi

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token
          gh auth status

      - name: Check First Codespace
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Fetching first codespace..."
          CODESPACE_NAME=$(gh codespace list --json name --jq '.[0].name' 2>/dev/null || echo "")
          if [ -n "$CODESPACE_NAME" ] && [ "$CODESPACE_NAME" != "null" ]; then
            echo "Found codespace: $CODESPACE_NAME"
            gh codespace view -c "$CODESPACE_NAME"
            echo "Connecting via SSH and running commands..."
            gh codespace ssh -c "$CODESPACE_NAME" -- "ls -la && pwd && whoami && df -h"
            sleep 60
          else
            echo "No codespaces found"
            gh codespace list || echo "Failed to list codespaces"
            exit 1
          fi

  trigger_next_chunk:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ always() && needs.deploy.result == 'success' }}
    steps:
      - name: Trigger next chunk or complete
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const currentPart = "${{ github.event.inputs.part || '01' }}";
            let nextPartNumber;

            console.log(`Current part: ${currentPart}`);

            if (currentPart === "all") {
              console.log("Initial 'all' detected, starting with part 001.");
              nextPartNumber = 1;
            } else {
              nextPartNumber = parseInt(currentPart) + 1;
            }

            console.log(`Next part number: ${nextPartNumber}`);

            if (nextPartNumber <= 63000000) { 
              const nextPartStr = String(nextPartNumber).padStart(3, '0');
              console.log(`Triggering next chunk: ${nextPartStr}`);
              
              try {
                await github.rest.actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: 'main.yml',
                  ref: 'main',
                  inputs: { 
                    part: nextPartStr 
                  }
                });
                console.log(`Successfully triggered workflow for part ${nextPartStr}`);
              } catch (error) {
                console.error(`Failed to trigger workflow: ${error.message}`);
                throw error;
              }
            } else {
              console.log("All chunks processed. Workflow sequence completed.");
            }
