name: Codespace Auto-Run

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:
    inputs:
      part:
        description: 'Part number (01, 02, etc.)'
        required: false
        default: '01'
  push:
    branches:
      - main
      - develop

jobs:
  auto-run:
    runs-on: ubuntu-latest
    steps:
      # Step 0: Setup environment and display start time
      - name: Display Start Time
        run: |
          echo "=== GitHub Codespace Auto-Run Script ==="
          echo "Start time: $(date)"

      # Step 1: Install required packages
      - name: Install Required Packages
        run: |
          echo "[1/5] Installing required packages..."
          sudo apt-get update -y
          sudo apt-get install -y stress curl git jq

      # Step 2: Install GitHub CLI if not present
      - name: Install GitHub CLI
        run: |
          echo "[2/5] Installing GitHub CLI..."
          if ! command -v gh >/dev/null 2>&1; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
              sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] \
              https://cli.github.com/packages stable main" | \
              sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt-get update -y
            sudo apt-get install gh -y
          else
            echo "GitHub CLI is already installed."
          fi

      # Step 3: Verify GitHub CLI Authentication
      - name: Verify GitHub CLI Authentication
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "[3/5] Verifying GitHub CLI authentication..."
          if [ -z "$GH_TOKEN" ]; then
            echo "Error: GH_TOKEN is not set or empty"
            exit 1
          fi
          echo "Token length: ${#GH_TOKEN}"
          echo "Testing authentication with 'gh auth status'..."
          gh auth login --with-token < <(echo "$GH_TOKEN")
          gh auth status

      # Step 4: Get and Check First Codespace
      - name: Check First Codespace
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "[4/5] Getting first available codespace..."
          CODESPACE_NAME=$(gh cs list --json name --jq '.[0].name' 2>/dev/null || echo "")
          
          if [ -n "$CODESPACE_NAME" ] && [ "$CODESPACE_NAME" != "null" ]; then
            echo "Found codespace: $CODESPACE_NAME"
            gh cs view -c "$CODESPACE_NAME"
            echo "Connecting to codespace via SSH and running commands..."
            gh cs ssh -c "$CODESPACE_NAME" -- ls -la && pwd && whoami && df -h
            echo "Sleeping for 60 seconds..."
            sleep 60
            echo "Sleep completed, workflow finished
